sudo: required
services:
- docker

env:
- os_version=16.04
- os_version=18.04

install:
- docker image build -t test -f test.dockerfile
  --build-arg "os_version=$os_version" .

before_script:
- container=$(docker container run -d --init test)

script:
# Install twice
- install=true
- &run docker container exec -it $container
  ansible-playbook test.yml -i inventory.cfg -v -e install=$install
- *run
# Uninstall twice
- install=false
- *run
- *run

after_script:
- docker container stop $container
