sudo: required
services:
  - docker
language: python
python:
  - "3.6"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
script:
  - docker container run --rm -it
      -v /var/run/docker.sock:/var/run/docker.sock:ro
      -v $(pwd):/role:ro
      tecnativa/ansible-test-playground:lifecycle
      apply.yml unapply.yml destroy.yml
