- name: (un)install docker compose
  pip:
    name: docker-compose
    state: "{{ docker_compose_state }}"
    version: "{{ docker_compose_version if 'ubuntu2204' not in group_names else omit }}"

- name: check docker compose is installed correctly
  command: docker-compose --version
  changed_when: false
  when:
  - docker_compose_state != 'absent'
