- name: (un)install docker compose
  pip:
    name: docker-compose
    state: "{{ docker_compose_state }}"
    version: "{{ docker_compose_version }}"

- name: check docker compose is installed correctly
  command: docker-compose --version
  changed_when: false
  when:
    - docker_compose_state != 'absent'
