- when:
  - docker_machine_state == 'present'
  block:
  - name: check current docker machine installation
    command: "{{ docker_machine_path|quote }} --version"
    changed_when: false
    ignore_errors: true
    register: result

  - name: install docker machine
    get_url:
      checksum: "sha256:{{
        lookup('vars', 'docker_machine_checksum_' + ansible_architecture)
      }}"
      dest: "{{ docker_machine_path }}"
      group: "{{ ansible_user }}"
      mode: a=rx,u+w
      owner: "{{ ansible_user }}"
      url: >
        https://github.com/docker/machine/releases/download/v
        {{- docker_machine_version -}}
        /docker-machine-{{ ansible_system }}-{{ ansible_architecture }}
    when:
    - result.failed|d(False) or
      not result.stdout.startswith(
        'docker-machine version %s,'|format(docker_machine_version)
      )

  - name: check docker machine is installed correctly
    command: "{{ docker_machine_path|quote }} --version"
    changed_when: false

- name: uninstall docker machine
  file:
    path: "{{ docker_machine_path }}"
    state: absent
  when:
  - docker_machine_state == 'absent'
