- name: update grub
  command: update-grub
  when:
    - docker_bootloader == 'grub'

- name: reload systemd
  systemd:
    daemon_reload: true

- name: (dis/en)able udev cleanup timer
  service:
    name: udev-cleanup.timer
    enabled: "{{ docker_engine_state == 'present' }}"
  ignore_errors: "{{ not docker_engine_state == 'present' }}"

- name: (dis/en)able dockerd
  service:
    name: docker
    enabled: "{{ docker_engine_state == 'present' }}"
    state: "{{ 'started' if docker_engine_state == 'present' else 'stopped' }}"
  # HACK to pass idempotency test in `unapply.yml`
  # TODO remove when https://github.com/ansible/ansible/issues/31344 is fixed
  register: result
  changed_when: "result.changed and docker_engine_state == 'present'"
  retries: 4
  delay: 5

- name: reload dockerd
  service:
    name: docker
    enabled: true
    state: reloaded
  when:
    - docker_engine_state == 'present'

- name: restart journald
  service:
    name: systemd-journald
    enabled: true
    state: restarted
  delay: 3
  register: journald_restart
  retries: 5
  until: journald_restart.changed
