- name: update grub
  command: update-grub
  ignore_errors: &testing_mode "{{ docker_role._testing_mode }}"

- name: reload dockerd
  service:
    name: docker
    enabled: true
    state: reloaded
  ignore_errors: *testing_mode
  when:
  - docker_role.engine.present

- name: restart journald
  service:
    name: systemd-journald
    enabled: true
    state: restarted
  delay: 3
  ignore_errors: *testing_mode
  register: journald_restart
  retries: "{{ 1 if docker_role._testing_mode else 5 }}"
  until: journald_restart.changed
