- name: update grub
  command: update-grub

- name: reload dockerd
  service:
    name: docker
    enabled: true
    state: reloaded
  ignore_errors: *testing_mode
  when:
  - docker_role.engine.present

- name: restart journald
  service:
    name: systemd-journald
    enabled: true
    state: restarted
  delay: 3
  ignore_errors: *testing_mode
  register: journald_restart
  retries: 5
  until: journald_restart.changed
