- name: obtain docker info
  command: docker info --format {{ "{{json .}}"|quote }}
  changed_when: false
  register: docker_info

- name: obtain swarm manager join command
  command: docker swarm join-token manager
  register: join_manager
  changed_when: false
  failed_when: false

- name: obtain swarm worker join command
  command: docker swarm join-token worker
  register: join_worker
  changed_when: false
  failed_when: false

- name: process docker facts
  set_fact:
    docker_info: "{{ docker_info.stdout|from_json }}"
    join_manager: "{{ join_manager.stdout_lines[2]|d('')|trim }}"
    join_worker: "{{ join_worker.stdout_lines[2]|d('')|trim }}"
