- import_tasks: present.yml
  when:
    - docker_role.engine.present
    - docker_role.swarm.present

- import_tasks: leave.yml
  when:
    # If engine is absent, the swarm should already be absent
    - docker_role.engine.present
    - not docker_role.swarm.present
