- import_tasks: present.yml
  when:
    - docker_engine_state != 'absent'
    - docker_swarm_state != 'absent'

- import_tasks: leave.yml
  when:
    # If engine is absent, the swarm should already be absent
    - docker_engine_state != 'absent'
    - docker_swarm_state == 'absent'
